
#Clean
clean:
#	del /obj/*.*
#	del /bin/*

#Default Build of Excutable
bin:
	@echo HI

#Mac-build
mac_bin:
	
#Linux-build
linux_bin:
	
#Windows-build
win_bin:
	

	
#Execute
run:
	
test: